context:
  name: csp-adapter-telegram
  version: "0.2.0"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/csp-adapter-telegram/csp_adapter_telegram-${{ version }}.tar.gz
  sha256: dd90518326943fb9da6bb244bb0e712bb58d17bf6ce1f11d5257b6dc7130a2a1

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - chatom
    - csp
    - python-telegram-bot
    - pydantic >=2

tests:
  - python:
      imports:
        - csp_adapter_telegram
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: CSP adapter for Telegram
  homepage: https://github.com/timkpaine/csp-adapter-telegram
  repository: https://github.com/timkpaine/csp-adapter-telegram

extra:
  recipe-maintainers:
    - timkpaine
